config:
  name: TwoTowerRec

  entities_person: /home/zy/data2/yyr/codes/kg4proj-rec/data/data/nsfkg/entities_person.pkl
  entities_project: /home/zy/data2/yyr/codes/kg4proj-rec/data/data/nsfkg/entities_project.pkl
  train_data: /home/zy/data2/yyr/codes/kg4proj-rec/data/data/nsfkg/train_rel_is_principal_investigator_of.pkl
  val_data: /home/zy/data2/yyr/codes/kg4proj-rec/data/data/nsfkg/val_rel_is_principal_investigator_of.pkl
  test_data: /home/zy/data2/yyr/codes/kg4proj-rec/data/data/nsfkg/test_rel_is_principal_investigator_of.pkl

  epochs: 1000
  batch_size: 64
  test_batch_size: 64

  bert_path: ./pretrained_model/bert-base-cased

  lr: !!float
    1e-4
  gamma: 0.7
  seed: 1
  save_path: ./save
  gpu: 1
  adam_epsilon: !!float
    1e-6
  warmup_ratio: 0.06
  weight_decay: !!float
    1e-5
  
  